// Generated by CoffeeScript 1.10.0
var boundings, buttons, create, initButtonPlay, isSmallScreen, toggleFullScreen, updateBoundings;

buttons = {
  play: null,
  player1_left: null,
  player1_right: null,
  player2_left: null,
  player2_right: null
};

boundings = {
  play: {
    height: 0,
    width: 0
  },
  arrows: {
    height: 0,
    width: 0
  },
  game: {
    height: 0,
    width: 0
  }
};

create = function() {
  console.log('Create');
  game.scale.fullScreenScaleMode = Phaser.ScaleManager.EXACT_FIT;
  updateBoundings();
  return initButtonPlay();
};

initButtonPlay = function() {};

isSmallScreen = function() {
  return window.innerHeight < 768;
};

toggleFullScreen = function() {
  if (game.scale.isFullScreen) {
    return game.scale.stopFullScreen();
  } else {
    return game.scale.startFullScreen(false);
  }
};

updateBoundings = function() {};

//# sourceMappingURL=create.js.map
