// Generated by CoffeeScript 1.10.0
var preload;

preload = function() {
  console.log('Preload');
  game.load.image('fleche_gauche', 'assets/fleche_gauche.png');
  return game.load.image('fleche_droite', 'assets/fleche_droite.png');
};

//# sourceMappingURL=preload.js.map
