// Generated by CoffeeScript 1.10.0
var GamePlay, listenerBoutonD, listenerBoutonG;

GamePlay = (function() {
  function GamePlay(game1) {
    this.game = game1;
    if (debug) {
      console.log('GamePlay::construct()');
    }
  }

  GamePlay.prototype.preload = function() {
    if (debug) {
      console.log('GamePlay::preload()');
    }
    game.load.image('fleche_gauche', 'assets/fleche_gauche.png');
    return game.load.image('fleche_droite', 'assets/fleche_droite.png');
  };

  GamePlay.prototype.create = function() {
    var moteur;
    if (debug) {
      console.log('GamePlay::create()');
    }
    moteur = new tronEngine();
    spriteG.inputEnabled = true;
    spriteG.events.onInputDown.add(listenerBoutonG, this);
    spriteD.inputEnabled = true;
    return spriteD.events.onInputDown.add(listenerBoutonD, this);
  };

  return GamePlay;

})();

listenerBoutonG = function() {
  return console.log("bonton gauche");
};

listenerBoutonD = function() {
  console.log("bonton droit");
  return {
    update: function() {
      var spriteD, spriteG;
      if (debug) {
        console.log('GamePlay::update()');
      }
      spriteG = game.add.sprite(0, 0, 'fleche_gauche');
      spriteG.scale.setTo(0.2, 0.2);
      spriteD = game.add.sprite(50, 0, 'fleche_droite');
      return spriteD.scale.setTo(0.2, 0.2);
    }
  };
};

//# sourceMappingURL=GamePlay.js.map
