// Generated by CoffeeScript 1.10.0
var GameTitle;

GameTitle = (function() {
  function GameTitle() {}

  GameTitle.prototype.preload = function() {};

  GameTitle.prototype.create = function() {};

  GameTitle.prototype.update = function() {};

  return GameTitle;

})();

//# sourceMappingURL=GameTitle.js.map
