// Generated by CoffeeScript 1.10.0
var GameTitle;

GameTitle = (function() {
  function GameTitle(game) {
    this.game = game;
    if (debug) {
      console.log('GameTitle::constructor()');
    }
  }

  GameTitle.prototype.preload = function() {
    if (debug) {
      console.log('GameTitle::preload()');
    }
    return this.game.load.image('buttonPlay', '/assets/img/buttonPlay.png');
  };

  GameTitle.prototype.create = function() {
    if (debug) {
      console.log('GameTitle::create()');
    }
    this.buttonPlay = this.game.add.button(this.game.world.centerX, this.game.world.centerY, 'buttonPlay', this.onButtonPlayClick, this, 0, 1, 2);
    return this.buttonPlay.anchor.setTo(0.5, 0.5);
  };

  GameTitle.prototype.update = function() {
    if (debug) {
      return console.log('GameTitle::update()');
    }
  };

  GameTitle.prototype.onButtonPlayClick = function() {
    return console.log('Jouer');
  };

  return GameTitle;

})();

//# sourceMappingURL=GameTitle.js.map
