// Generated by CoffeeScript 1.10.0
var Boot;

Boot = (function() {
  function Boot(game) {
    this.game = game;
    if (debug) {
      console.log("Boot::constructor()");
    }
  }

  Boot.prototype.preload = function() {
    if (debug) {
      return console.log("Boot::preload()");
    }
  };

  Boot.prototype.create = function() {
    if (debug) {
      console.log("Boot::create()");
    }
    this.game.scale.fullScreenScaleMode = Phaser.ScaleManager.EXACT_FIT;
    return this.game.state.start("GamePlay");
  };

  return Boot;

})();

//# sourceMappingURL=Boot.js.map
