// Generated by CoffeeScript 1.10.0
var Boot;

Boot = (function() {
  function Boot(game) {
    this.game = game;
    if (debug) {
      console.log('Boot::constructor()');
    }
  }

  Boot.prototype.preload = function() {
    if (debug) {
      return console.log('Boot::preload()');
    }
  };

  Boot.prototype.create = function() {
    var timer;
    if (debug) {
      console.log('Boot::create()');
    }
    timer = this.game.time.create();
    timer.add(1000, function() {
      return this.game.state.start('GameTitle');
    }, this);
    return timer.start();
  };

  return Boot;

})();

//# sourceMappingURL=Boot.js.map
